services:
  mysql:
    image: 'mysql:latest'
    container_name: save_mysql
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "18000:3306"
    environment:
      - MYSQL_DATABASE=save
      - MYSQL_USER=save
      - MYSQL_PASSWORD=save123456
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
    profiles:
      - dev
      - release

  redis:
    image: redis:8
    container_name: save_redis
    ports:
      - "18003:6379"
    volumes:
      - ./pkg/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./pkg/data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    profiles:
      - dev
      - release

  save:
    image: save:latest
    container_name: save_main
    depends_on:
      - mysql
      - redis
    restart: always
    network_mode: host
    profiles:
      - release