services:
  mysql:
    image: 'mysql:latest'
    container_name: save_mysql
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "18000:3306"
    environment:
      - MYSQL_DATABASE=save
      - MYSQL_USER=save
      - MYSQL_PASSWORD=save123456
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
    profiles:
      - dev
      - release

  save:
    image: save:latest
    container_name: save_main
    depends_on:
      - mysql
    restart: always
    network_mode: host
    profiles:
      - release